services:
  # MySQL
  dbTasks:
    platform: linux/x86_64
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks
      MYSQL_USER: nath
      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - "./docker/dbTasks/data:/var/lib/mysql"
      - "./docker/dbTasks/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./docker/dbTasks/sql:/docker-entrypoint-initdb.d"

  adminer:
    image: adminer
    container_name: adminer-tasks
    ports:
      - "8080:8080"
    